config/routes.rb
Rails.application.routes.draw do
  resources :applications
  resources :roles
  post '/roles/destory_all' => 'roles#destory_all', as: 'destory_all'

  devise_for :users, controllers: {registrations: 'registrations',passwords: 'passwords'}
  namespace :admin do
    get '/' => 'users#index'
    resources :users
    resources :organizations
  end
  get '/applications/:id/roles_users' => 'roles_users#index', as: 'roles_users'
  post '/applications/:id/roles_users/create' => 'roles_users#create'
  delete '/applications/:id/roles_users/destroy' => 'roles_users#destroy' ,as: 'destroy_role_user'
  post '/applications/delete_attachment' => 'applications#delete_attachment', as: 'delete_attachment'

  devise_scope :user do
    root "devise/sessions#new"
  end

end

app/models/organization.rb
class Organization < ActiveRecord::Base
	has_many :users
	has_many :applications
	has_many :roles
	accepts_nested_attributes_for :users

	validates :domain, :presence => true, :uniqueness => true

end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /admin/organizations
  # GET /admin/organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /admin/organizations/1
  # GET /admin/organizations/1.json
  def show
  end

  # GET /admin/organizations/new
  def new
    @organization = Organization.new
  end

  # GET /admin/organizations/1/edit
  def edit
  end

  # POST /admin/organizations
  # POST /admin/organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/organizations/1
  # PATCH/PUT /admin/organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/organizations/1
  # DELETE /admin/organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params[:organization]
    end
end

app/views/admin/organizations/_form.html.erb
<%= form_for([:admin, @organization]) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit 'Save' %>
<% end %>

app/views/admin/organizations/edit.html.erb
<h3>Editing Organization</h3>
<%= render 'form' %>
<%= link_to 'Show', admin_organization_path(@organization) %>
\|
<%= link_to 'Back', admin_organizations_path %>

app/views/admin/organizations/index.html.erb
<h1>Listing Organizations</h1>
<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Actions</th>
  </tr>
  <% @organizations.each do |organization| %>
    <tr>
      <td>
        <%= organization.name %>
      </td>
      <td>
        <%= organization.description || "--" %>
      </td>
      <td>
        <%= link_to 'Show', admin_organization_path(organization), :class => "btn btn-primary btn-xs" %>
        <%= link_to 'Edit', edit_admin_organization_path(organization), :class => "btn btn-primary btn-xs" %>
        <%= link_to 'Delete', admin_organization_path(organization), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "btn btn-primary btn-xs" %>
      </td>
    </tr>
  <% end %>
</table>
<br/>
<%= link_to 'New Organization', new_admin_organization_path %>

app/views/admin/organizations/new.html.erb
<h1>New admin_organization</h1>
<%= render 'form' %>
<%= link_to 'Back', admin_organizations_path %>

app/views/admin/organizations/show.html.erb
<p id="notice">
  <%= notice %>
</p>
<%= link_to 'Edit', edit_admin_organization_path(@organization) %>
\|
<%= link_to 'Back', admin_organizations_path %>