config/routes.rb
Rails.application.routes.draw do
  resources :applications
  resources :roles
  post '/roles/destory_all' => 'roles#destory_all', as: 'destory_all'

  devise_for :users, controllers: {registrations: 'registrations',passwords: 'passwords'}
  namespace :admin do
    get '/' => 'users#index'
    resources :users
    resources :organizations
  end
  get '/applications/:id/roles_users' => 'roles_users#index', as: 'roles_users'
  post '/applications/:id/roles_users/create' => 'roles_users#create'
  delete '/applications/:id/roles_users/destroy' => 'roles_users#destroy' ,as: 'destroy_role_user'
  post '/applications/delete_attachment' => 'applications#delete_attachment', as: 'delete_attachment'

  devise_scope :user do
    root "devise/sessions#new"
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  has_and_belongs_to_many :permissions
  belongs_to :organization

  validates_presence_of :name
  validates_uniqueness_of :name, scope: :organization_id

  def super_admin_org_admin(current_user)
  	result = current_user.is_super_admin? && self.name == 'super_admin'
  	if result == false
  		result = current_user.is_organization_admin? && self.name == 'organization_admin'
  	end
  	result
  end
  
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
	before_action :set_role, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /roles
  # GET /roles.json
  def index
    if current_user.is_super_admin?
      @roles = Role.all
    else
      @roles = current_user.organization.roles
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
    set_action_permission
    render :layout => !request.xhr?
  end

  # GET /roles/1/edit
  def edit
    set_action_permission
    render :layout => !request.xhr?
  end

  # POST /roles
  # POST /roles.json
  def create
    @role =  Role.new(role_params)
    @role.organization_id = current_user.organization.id
    if @role.save
      role_permission_mappings(params[:permission])
    end
    set_action_permission
    respond_with(@role)
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    set_action_permission
    if @role.update(role_params)
      role_permission_mappings(params[:permission])
    end
    respond_with(@role)
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role sample was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def role_permission_mappings(permission_ids=[])
    @role.permissions.delete_all
    permission_ids.each do |p_id|
      permission = Permission.find_by_id(p_id.to_i)
      @role.permissions << permission unless @role.permissions.include?(permission)
    end
  end

  def destory_all
    params[:role_id].each do |role_id|
      @role =  Role.find_by_id(role_id).destroy
    end
    render js: "window.location = '#{roles_url}'"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    def set_action_permission
      @all_actions = StaticData::ACTIONS
      @permissions = Permission.all.group('subject_class')
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :description,:organization_id)
    end
end

app/helpers/role_helper.rb
module RoleHelper
end

app/views/roles/_form.html.erb
<div class="rc-main">
 <%= form_for @role, remote: true do |f| %>
  <div class="rc-head">
    <% if @role.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% @role.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <table width="700" border="0" cellspacing="0" cellpadding="0" align="center">
      <tr style="background:none;">
        <td align="right">Role Name</td>
        <td>
          <%= f.text_field :name , :class=>"form-style1" %>
        </td>
        <td align="right">Description</td>
        <td><%= f.text_area :description,  :class=>"form-style1"%></td>
      </tr>
    </table>      
  </div>

  <table class="tbl-1 tbl-1-border alternate-color" width="100%" border="0" cellspacing="0" cellpadding="0" style="float:left;">
    <tr>
      <th align="left" valign="middle"></th>
      <%i = 1%>
      <% all_actions.each do |const|%>
        <th align="center" valign="middle"><input name="" type="checkbox" value="" id= "all" class="all_actions" 
        const="<%=const%>"/><%=const%></th>
        <%i+=1%>
       <% end %>
    </tr>
    <% permissions.each do |permission|%>
      <% subject_permission = permission.get_all_permissions%>
      <tr>
        <td width="200px" class="head"><%= permission.subject_class %></td>
        <%j=0%>
        <% all_actions.count.times do %>
          <td align="center">
            <% if subject_permission.map{|p| p.action}.include?all_actions[j]%>
              <%sub = permission.get_permission_with_action(all_actions[j])%>
              <% if @role.permissions.find_by_id(sub.id).blank? %>
                <input name="permission[]" type="checkbox" value="<%=sub.id%>" class="<%= sub.action%>"/>
              <%else%>
                <input name="permission[]" type="checkbox" value="<%=sub.id%>" checked="checked" class="<%= sub.action%>"/>
              <%end%>
            <%end%>
          </td>
          <%j+=1%>
        <%end%>
      </tr>
    <% end %>
 </table> 
 <% end %>
</div>

<script type="text/javascript">
  $('.all_actions').click(function() {
    var all= '.'+$(this).attr('const')
    if (this.checked) {
      $(all).each(function() {
        this.checked = true;
      });
    } else {
      $(all).each(function() {
        this.checked = false;
      });
    }
  });
</script>

app/views/roles/create.js.erb
<% if @role.errors.any? -%>
  $("#role_form").html("<%= escape_javascript(render partial: 'form', locals: { role: @role ,all_actions: @all_actions,permissions: @permissions})%>");
<% else -%>
  $(window.location.reload("/roles"))
<% end -%>

app/views/roles/edit.html.erb
<%= render 'form' ,{all_actions: @all_actions,permissions: @permissions}%>

app/views/roles/index.html.erb
<div class="content-wrapper" style="margin-top:0px;">
  <div class="cnt-head">
    <h1>Roles</h1>
    <label id="delete_role"><span><img src="/assets/button_minus_red.png" width="16" height="16" alt="plus" /></span>Delete Role</label>
    <label id="new_role"><span><img src="/assets/plus-icon.png" width="16" height="16" alt="plus" /></span>New Role</label>
  </div>

  <table class="tbl-1 alternate-color" cellpadding="0px" cellspacing="0px">
    <thead>
      <tr>
        <th align="left" width="20px;"><%= check_box_tag "all_roles", 'all_roles' %></th>
        <th align="left" width="250px;">Name</th>
        <th align="left">Description</th>
      </tr>
    </thead>

    <tbody>
      <% @roles.each do |role| %>
        <tr>
          <td align="left">
            <%unless role.super_admin_org_admin(current_user)%>
              <input name="role" type="checkbox" id="<%= role.id%>" class="roles" value="<%= role.id%>"/>
            <%end%>
          </td>
          <td align="left"><%= link_to role.name,edit_role_path(role), class: "edit_role" %></td>
          <td align="left"><%= role.description %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<script type="text/javascript">

 function submitForm() {
    $(this).find("form").submit();
  }

 $("#new_role").on("click", function (e) {
    e.preventDefault();
    var tag = $("<div id=\"role_form\"></div>"),
      url = 'roles/new';
    $.ajax({
      url: url,
      success: function(data) {
        tag.html(data).dialog({
          modal: true,
          height: 600,
          width: 950,
          title: 'Create Role',
          open: function (event, ui) {
            $('.ui-widget-overlay').addClass('override');
          },
          buttons: [
            {
              text: "Save",
              "class": 'btn-style',
              click: submitForm
            },
            {
              text: "Cancel",
              "class": 'btn-style-2',
              click: function() {
                $(this).dialog("close")
              }
            }
          ]
        }).
        dialog('open');
      }
    });
  });

 $(".edit_role").on("click", function (e){
      e.preventDefault();
      var tag = $("<div id=\"role_form\"></div>"),
        url = $(this).attr('href');
      $.ajax({
        url: url,
        success: function(data) {
          tag.html(data).dialog({modal: true,
            height: 600,
            width: 950,
            title: 'Edit Role',
            open: function (event, ui) {
              $('.ui-widget-overlay').addClass('override');
            },
            buttons: [
              {
                text: "Save Role",
                "class": 'btn-style',
                click: submitForm
              },
              {
                text: "Cancel",
                "class": 'btn-style-2',
                click: function() {
                  $(this).dialog("close")
                }
              }
            ]
          }).
          dialog('open');
        }
      });
    });

  $('#all_roles').click(function() {
    if (this.checked) {
      $('.roles').each(function() {
        this.checked = true;
      });
    } else {
      $('.roles').each(function() {
        this.checked = false;
      });
    }

  });

  $('#delete_role').on("click", function(e) {
    var valueSelector = function() { return this.value; };
    var roleIds = $("input:checkbox[class=roles]:checked").map(valueSelector).get();
    if(roleIds == ''){
      alert("Please select atleast one role");
      return false;
    }
    e.preventDefault();
    if(confirm("Are you sure?Corresponding users and permissions data will delete.")){
      $.ajax('/roles/destory_all', {
        type: 'POST',
        datatype: 'json',
        data: {role_id: roleIds},
        success: function(data, textStatus, jqHXR) {
           $(window.location.reload("/roles"))
        }
      });
    }
  });
</script>

app/views/roles/new.html.erb
<%= render 'form' ,{all_actions: @all_actions,permissions: @permissions}%>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @role.description %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

app/views/roles/update.js.erb
<% if @role.errors.any? -%>
  $(document).find("#role_form").html("<%= escape_javascript(render partial: 'form', locals: { role: @role, all_actions: @all_actions, permissions: @permissions })%>");
<% else -%>
  $(window.location.reload("/roles"))
<% end -%>