config/routes.rb
Rails.application.routes.draw do
  resources :applications
  resources :roles
  post '/roles/destory_all' => 'roles#destory_all', as: 'destory_all'

  devise_for :users, controllers: {registrations: 'registrations',passwords: 'passwords'}
  namespace :admin do
    get '/' => 'users#index'
    resources :users
    resources :organizations
  end
  get '/applications/:id/roles_users' => 'roles_users#index', as: 'roles_users'
  post '/applications/:id/roles_users/create' => 'roles_users#create'
  delete '/applications/:id/roles_users/destroy' => 'roles_users#destroy' ,as: 'destroy_role_user'
  post '/applications/delete_attachment' => 'applications#delete_attachment', as: 'delete_attachment'

  devise_scope :user do
    root "devise/sessions#new"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :is_organization_admin
	belongs_to :organization
  has_one :profile
  has_and_belongs_to_many :roles, join_table: :users_roles, dependent: :destroy
  accepts_nested_attributes_for :profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  apply_simple_captcha :add_to_base => true
  delegate :first_name, :last_name, :referred_by, :mobile_number, :telephone_number, :gender, :user, to: :profile, allow_nil: true

  validates_format_of :email, without: /(\W|^)[\w.+\-]{0,25}@(yahoo|hotmail|gmail)\.com(\W|$)/, :message => 'Please enter a valid office address', allow_blank: true, if: :email_changed?
  validates :organization_id, :presence => true
  validates_format_of :password, with: /\A(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*(_|[-+_!@#$%^&*.,?])).+\z/,
    :message => "must include at least one lowercase letter, one uppercase letter, and one digit and one special character",
    allow_blank: true

  def full_name
    first_name.to_s + last_name.to_s if (first_name || last_name)
  end

  def is_organization_admin?
    self.has_role?(:organization_admin, organization)
  end

  def is_super_admin?
    self.has_role?(:super_admin)
  end

  def find_roles(app_id)
    roles = []
    unless app_id.blank?
      roles_users = RolesUser.where(application_id: app_id,user_id: self.id)
      if roles_users.blank?
        roles = []
      else
        role_ids = roles_users.map{|ur| ur.role_id}
        roles = Role.where(id: role_ids)
      end
    end
  end

  def has_role?(role_name,organization=nil)
    if organization.blank?
      number_of_roles = self.roles.where(name: role_name).count
    else
      number_of_roles = self.roles.where(name: role_name, organization_id: organization.id).count
    end
    (number_of_roles == 0) ? false : true
  end

  def add_role(role_name,organization=nil)
    if role_name.to_s.downcase == 'super_admin'
      role = Role.create(name: role_name)
    else
      role = Role.create(name: role_name, organization_id: organization.id)
    end
    self.roles << role unless role.blank?
  end

  def is_organization_admin
    is_organization_admin?
  end

  # def is_organization_admin=(val)
    # admin_role = Role.where(name: 'organization_admin', organization_id: organization.id).first_or_create
    # if val.to_i == 0
    #   self.roles.delete(admin_role)
    # else
    #   self.roles << admin_role
    # end
  # end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /users
  # GET /users.json
  def index
    @user = User.new
    @organizations = current_user.is_super_admin? ? Organization.all : [current_user.organization]
    @user.build_profile if @user.profile.blank?
    if current_user.is_super_admin?
      @users = User.all
    # elsif current_user.is_organization_admin?
    #   @users = current_user.organization.users
    else
      @users = User.where("created_by = #{current_user.id} or id = #{current_user.id}")
    end
  end

  def show
  end

  def new
  end


  def edit
    render :layout => !request.xhr?
  end

  def create
    @user = User.new(user_params)
    @user.organization_id = current_user.organization_id if @user.organization_id.blank?
    generated_password = Devise.friendly_token.first(8)+"#"+"2"
    @user.password =  generated_password
    @user.created_by = current_user.id
    respond_to do |format|
      if @user.save
        create_or_delete_role_mapping(params[:user][:is_organization_admin])
        UserMailer.welcome_email(@user, generated_password).deliver
        #flash[:notice] = flash[:notice].to_a.concat @user.errors.full_messages
        format.html { redirect_to admin_users_path, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
        format.js
      else
        #flash[:notice] = flash[:notice].to_a.concat @user.errors.full_messages
        format.html { render :action => "new"}
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    if params[:user][:password].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
    end
    old_org = @user.organization_id
    respond_to do |format|
      if @user.update(user_params)
        delete_roles unless old_org == @user.organization_id
        create_or_delete_role_mapping(params[:user][:is_organization_admin])
        UserMailer.update(@user, params[:user][:password]).deliver
        format.html { redirect_to admin_users_path, :notice => 'User was successfully updated.' }
        format.json { head :ok }
        format.js
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :ok }
    end
  end

  def create_or_delete_role_mapping(organization_admin)
    admin_role = Role.where(name: 'organization_admin', organization_id: @user.organization.id).first_or_create
    if organization_admin.to_i == 0
      @user.roles.delete(admin_role)
    else
      @user.roles << admin_role
    end
  end
  #delete user related roles, when user changes to other organizations
  def delete_roles
   @user.roles.destroy_all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :organization_id,:is_organization_admin, profile_attributes: [:first_name, :last_name,:mobile_number] )
    end
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user], :remote => true do |f| -%>
  <%- unless f.object.errors.empty? %>
    <div class='ui-state-highlight'>
      <%-f.object.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    </div>
  <% end %>
  <table border="0" cellspacing="7" cellpadding="0" align="center" width="400px">
    <tr>
      <td><%= f.label :email %></td>
      <td><%= f.text_field :email, class:'inpt-1' %></td>
    </tr>
    <%if current_user.is_super_admin? %>
        <tr>
         <td><%= f.label :organization %>
            <% selected = f.object.organization.blank? ? nil : f.object.organization.id%>
         </td>
         <td><%= f.collection_select :organization_id,Organization.all,:id ,:name,{selected: selected ,prompt: 'Please Select Organization'}%></td>
        </tr>
      <% end %>
    <%- f.object.profile || f.object.build_profile %>
    <%= f.fields_for :profile do |profile|%>
      <tr>
        <td><%= profile.label :first_name %></td>
        <td><%= profile.text_field :first_name, class:'inpt-1' %></td>
      </tr>
      <tr>
        <td><%= profile.label :last_name %></td>
        <td><%= profile.text_field :last_name, class:'inpt-1' %></td>
      </tr>

      <tr>
        <td><%= profile.label :mobile_number %></td>
        <td><%= profile.text_field :mobile_number, class:'inpt-1' %></td>
      </tr>
      <tr>
        <td><%= f.check_box :is_organization_admin %></td>
        <td><%= "Organization Admin" %></td>
      </tr>
    <% end %>
  </table>
<% end -%>

app/views/admin/users/_user.html.erb
 <tr>
  <td align="left"><%= user.first_name %></td>
  <td align="left"><%= user.last_name %></td>
  <td align="left"><%= user.email %></td>
  <td align="left"><%= user.mobile_number %></td>
  <td align="center">
    <%= link_to image_tag("edit.png", :border => 0), edit_admin_user_path(user), {class: "edit_user_link",title: "Edit",rel: 'tooltip',relative: true } if (action_active(user,'delete') || current_user== user)%>
  </td>
  <% unless current_user == user%>
    <td align="center">
      <%= link_to image_tag("delete.png", :border => 0), admin_user_path(user), {:method => :delete, title: "Delete",rel: "tooltip",relative: true, :data => { :confirm => 'Are you sure?'}} if action_active(user,'delete') %>
    </td>
  <%end%>
</tr>

app/views/admin/users/create.js.erb
<% if @user.errors.any? -%>
  $("#user_form").html("<%= escape_javascript(render :partial => 'form', :locals => {:user => @user})%>");
<% else -%>
  $(window.location.reload("/admin/users"))
<% end -%>

app/views/admin/users/edit.html.erb
<%= render 'form' %>

app/views/admin/users/index.html.erb
<div id="user_form" title="Users" style="display:none;">
   <%= render :partial => "form" %>
</div>
<div class="content-wrapper" style="margin-top:0px;">
  <div class="cnt-head">
    <h1>Users</h1>
    <% if action_active(current_user,'create') %>
    <label id="new_user"><span><img src="/assets/plus-icon.png" width="16" height="16" alt="plus" /></span>New User</label>
    <%end%>
   </div>
  <% if current_user.is_super_admin? %>
    <% @organizations.each do |organization|%>
      <div class="apl-main">
        <div class="apl-head show-user" organization-id="<%= organization.id%>">
          <label><img src="/assets/apl-head-icon2.png" width="12" height="12" alt="plus" id="image_icon"/></label>
            <%= organization.domain.split('.')[0].upcase %>
        </div>
      </div>
        <div class="user-detail-<%=organization.id%>" style="display: none;">
      <table class="tbl-1 alternate-color" id="users_list" border="0" cellspacing="0" cellpadding="0" style = "float:left;">
       <thead>
        <tr>
          <th align="left">First Name</th>
          <th align="left">Last Name</th>
              <th align="left">
            <%= t("activerecord.attributes.user.email", :default => t("activerecord.labels.email", :default => "Email")) %>
          </th>
          <th align="left">Mobile Number</th>
          <th align="left" colspan="2">Actions</th>
        </tr>
        </thead>
        <tbody>
        <% organization.users.each do |user| %>
          <%= render :partial => 'user', :locals => {user: user} %>
        <% end -%>
        </tbody>
      </table>
      <% if current_user.is_super_admin? %>
        </div>
      <%end%>
    <%end%>
  <%else%>
    <table class="tbl-1 alternate-color" id="users_list" border="0" cellspacing="0" cellpadding="0" style = "float:left;">
     <thead>
      <tr>
        <th align="left">First Name</th>
        <th align="left">Last Name</th>
            <th align="left">
          <%= t("activerecord.attributes.user.email", :default => t("activerecord.labels.email", :default => "Email")) %>
        </th>
        <th align="left">Mobile Number</th>
        <th align="left" colspan="2px">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
        <%= render :partial => 'user', :locals => {user: user} %>
      <% end -%>
      </tbody>
    </table>
  <%end%>

</div>

<script type="text/javascript">
  var dialog,form;
  $(function() {
    function submitForm() {
      dialog.find("form").submit()
    }

    function clearForm(){
      $("#user_form").html("<%= escape_javascript(render :partial => 'form')%>");
    }

    dialog = $( "#user_form" ).dialog({
      autoOpen: false,
      height: 450,
      width: 450,
      modal: true,
      open: function (event, ui) {
        $('.ui-widget-overlay').addClass('override');
      },
       title: 'Create User',
      buttons: {
          "Create User": submitForm,
          Cancel: function() {
            dialog.dialog( "close" );
          }
      },
      close: clearForm
    });

    $(document).on( "click", '#new_user', function() {
      dialog.dialog( "open" );
    });
   });


  $(document).on("click", ".edit_user_link", function(e) {
    e.preventDefault();
    var tag = $("<div id='user_edit_form'></div>"),
    url = $(this).attr('href')
     $.ajax({
       url: url,
       success: function(data) {
         tag.html(data).dialog({
           modal: true,
           height: 450,
           width: 450,
            open: function (event, ui) {
              $('.ui-widget-overlay').addClass('override');
            },
            title: 'Edit User',
           buttons: {
             "Save User": function(){ $(this).find("form").submit();},
             Cancel: function() {
               $(this).dialog('close');
             }
           },
         }).
         dialog('open');
       }
     });
  });


  $(document).on("click", '.show-user', function(e) {
    var organizationId = $(this).attr('organization-id')
    var finalDivId = ".user-detail-"+organizationId
    $(this).parent('div').parent().find(finalDivId).toggle();
    var plus = $(this).find('#image_icon').attr('src');
    if (plus == "/assets/apl-head-icon2.png")
    {
      $(this).find('#image_icon').removeAttr('src')
      $(this).find('#image_icon').attr('src','/assets/apl-head-icon1.png')
    }
    else 
    {
      $(this).find('#image_icon').removeAttr('src')
      $(this).find('#image_icon').attr('src','/assets/apl-head-icon2.png')
    }
   });

  </script>

app/views/admin/users/new.html.erb
<%= render 'form' %>

app/views/admin/users/show.html.erb
<label><%= t("activerecord.attributes.user.username", :default => t("activerecord.labels.username", :default => "User Name")) %> : </label>
<%= @user.username %><p/>
<label><%= t("activerecord.attributes.user.email", :default => t("activerecord.labels.email", :default => "Email")) %> : </label>
<%= @user.email %>



<div class="form-actions">
<%= link_to "Back", admin_users_path, :class => 'btn btn-sm btn-primary'  %>
<%= link_to "Edit", edit_admin_user_path(@user), :class => 'btn btn-sm btn-primary' %>
<% unless current_user == @user%>
<%= link_to "Delete", admin_user_path(@user), :method => "delete", :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-primary btn-sm' %>
<%end%>
</div>

app/views/admin/users/update.js.erb
<% if @user.errors.any? -%>
   $(document).find("#edit_user_form").html("<%= escape_javascript(render :partial => 'form', :locals => {:user => @user})%>");
<% else -%>
  $(window.location.reload("/admin/users"))
<% end -%>