config/routes.rb
Rails.application.routes.draw do
  resources :applications
  resources :roles
  post '/roles/destory_all' => 'roles#destory_all', as: 'destory_all'

  devise_for :users, controllers: {registrations: 'registrations',passwords: 'passwords'}
  namespace :admin do
    get '/' => 'users#index'
    resources :users
    resources :organizations
  end
  get '/applications/:id/roles_users' => 'roles_users#index', as: 'roles_users'
  post '/applications/:id/roles_users/create' => 'roles_users#create'
  delete '/applications/:id/roles_users/destroy' => 'roles_users#destroy' ,as: 'destroy_role_user'
  post '/applications/delete_attachment' => 'applications#delete_attachment', as: 'delete_attachment'

  devise_scope :user do
    root "devise/sessions#new"
  end

end

app/views/layouts/_head.html.erb
<meta charset="utf-8"/>
<meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<title>
  <%= content_for?(:title) ? yield(:title) : "Taas Pro" %>
</title>

<!-- Le HTML5 shim, for IE6-8 support of HTML elements
-->
<!--[if lt IE 9]
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
-->
<%= stylesheet_link_tag "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render partial: 'layouts/head' %>
</head>
<body>
<div class="main-wapper">
  <div class="main-wapper2">
    <div class="header-wrapper">
      <div class="header-top">
        <div class="header-top-nav">
          <ul id="nav">
            <li><a href="#"><span><img src="/assets/user-icon.png" width="14" height="14" alt="user" /></span><%= current_user.email%></a></li>
            <% if current_user.is_super_admin? || current_user.is_organization_admin? || action_active(current_user,"create")%>
              <li><a href="#"><span><img src="/assets/setting-icon.png" width="14" height="14" alt="settings" /></span>
              Administration</a>
                <ul>
                  <li><a href="<%= roles_path %>">Roles</a></li>
                  <li><a href="<%= admin_users_path%>">User Administration</a></li>
                </ul>
              </li>
            <%end%>
            <li><a href="#"><span><img src="/assets/setting-icon.png" width="14" height="14" alt="settings" /></span>Account Settings</a>
              <ul>
                <li><a  id="change_password" href="<%= edit_user_registration_path(current_user)%>">Change Password</a></li>
              </ul>
            </li>
            <%- if user_signed_in? %>
              <li><a href="<%= destroy_user_session_path %>" data-method='delete'><span><img src="/assets/logout-icon.png" width="14" height="14" alt="logout" /></span>Logout</a></li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="header-bottom">
        <div class="logo-main"> <img src="/assets/taaspro.png" width="176" height="51" alt="taaspro" /> </div>
        <div class="header-bottom-nav">
          <ul class="nav-tabs ">
            <li>
              <label><a href="#" style="height:15px;"><img src="/assets/home-icon.png" width="21" height="20" alt="home" /></a></label>
            </li>
            <li>
              <label class="active"><a href="<%= applications_path %>" class="active">My Apps</a></label>
            </li>
            <li>
              <label id="test_automation"><a href="#">Test Automation</a></label>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <%= yield %>
  </div>
</div>
<div class="footer"> Copyright 2014 · All rights reserved </div>
<script>
  function submitForm() {
      $(this).find("form").submit();
  }

  $("#change_password").on("click", function (e){
    e.preventDefault();
    var tag = $("<div id='paasword_change'></div>"),
      url = $(this).attr('href');
    $.ajax({
      url: url,
      success: function(data) {
        tag.html(data).dialog({modal: true,
          height: 400,
          width: 700,
          title: 'Edit Password',
          buttons: [
            {
              text: "Save Password",
              "class": 'btn-style',
              click: submitForm
            },
            {
              text: "Cancel",
              "class": 'btn-style-2',
              click: function() {
                $(this).dialog("close")
              }
            },
          ]
        }).
        dialog('open');
      }
    });
  });

  $("#test_automation").on("click", function (e) {
   var username = 'niranjan.g@techsophy.com'
   var password = 'Rabit@123' ;
   window.open('http://172.16.0.31:8955/rabit/login.html?username='+ username + '&password=' + password,'mywindow','width=$(window).width(),height=$(window).height()')
  });

  $('.header-bottom-nav').click(function (e) {
    $('ul.nav-tabs li.active').removeClass('active')
    $("#test_automation").addClass("active");
  });
</script>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render partial: 'layouts/head' %>
</head>
<body>

<%= yield %>

</body>
</html>